services:
  - type: web
    name: book-insight-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt && python manage.py migrate && python manage.py load_sample_books && python manage.py collectstatic --noinput"
    startCommand: "cd backend && gunicorn book_insight.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"