# Generated by Django 6.0.4 on 2026-04-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, max_length=300)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('num_reviews', models.IntegerField(default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('book_url', models.URLField(blank=True, max_length=1000)),
                ('cover_image_url', models.URLField(blank=True, max_length=1000)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('sentiment', models.CharField(blank=True, max_length=50)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
